package q39;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Test {
    public static void main(String[] args) throws SQLException {
        var url = "jdbc:mysql://localhost:3306/ocp";
        var user = "root";
        var password = "password";
        var sql = "SELECT ID FROM LOG";

        try (var con = DriverManager.getConnection(url, user, password);
//             var stmt = con.createStatement();
//             var stmt = con.prepareStatement(sql);
             var stmt = con.prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
             ) {
//            stmt.executeQuery(sql);

//            + Statement     createStatement()
//            + Statement     createStatement(int resultSetType, int resultSetConcurrency)
//            + Statement     createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)

//            + PreparedStatement     prepareStatement(String sql)
//            + PreparedStatement     prepareStatement(String sql, int autoGeneratedKeys)
//            + PreparedStatement     prepareStatement(String sql, int[] columnIndexes)
//            + PreparedStatement     prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
//            + PreparedStatement     prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
//            + PreparedStatement     prepareStatement(String sql, String[] columnNames)
        }
    }
}
